---
- hosts: servers
  become: true
  tasks: 
  - name: httpd
    yum:
      name: httpd
      state: present  

  - name: httpd start
    service:
      name: httpd
      state: started  

  - name: copy content
    copy: 
      dest: /var/www/html
      src: index.html
      
  - name: httpd start
    service: 
      name: httpd
      state: started

  
  
